spring:
  application:
    name: zeldle

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: none